# Generated by Django 5.2 on 2025-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='payload',
            field=models.JSONField(blank=True),
        ),
    ]
