# Generated by Django 5.2 on 2025-05-08 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clinic', '0002_alter_clinic_clinictype_alter_clinic_specialties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, max_length=20)),
                ('time', models.TimeField(auto_now_add=True, max_length=50)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('available', models.BooleanField(default=True, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now_add=True, max_length=50)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.clinic')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appointment', models.ForeignKey(limit_choices_to={'available': 'true'}, on_delete=django.db.models.deletion.CASCADE, to='Appointment.appointment')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
