# Generated by Django 5.2 on 2025-05-09 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentbooking',
            name='Appointment',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'patient'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='appointment',
            field=models.ForeignKey(limit_choices_to={'available': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.appointment'),
        ),
    ]
