# Generated by Django 5.2 on 2025-05-04 22:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UNDEFINED', max_length=50, unique=True)),
                ('clinictype', models.CharField(choices=[('indvisual', 'Indv'), ('healthcarecenter', 'Hccr')], default='indvisual', max_length=20)),
                ('address', models.TextField(default='UNDEFINED', max_length=100)),
                ('phoneNumber', models.CharField(default='UNDEFINED', max_length=15)),
                ('email', models.EmailField(default='UNDEFINED@UNDEFINED', max_length=100, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('specialties', models.CharField(default='UNDEFINED', max_length=100)),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text="Structured hours, e.g. {'mon': '9-5', 'tue': '10-4'}", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
