# Generated by Django 5.2 on 2025-05-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinictype',
            field=models.CharField(choices=[('individual', 'Indv'), ('healthcarecenter', 'Hccr')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='specialties',
            field=models.TextField(default='UNDEFINED', max_length=100),
        ),
    ]
