# Generated by Django 5.2 on 2025-06-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0002_alter_clinic_clinictype_alter_clinic_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_active',
            field=models.BooleanField(default=True, max_length=7),
        ),
    ]
