# Generated by Django 5.2 on 2025-06-08 19:46

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AI', '0001_install_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.TextField()),
                ('doctor', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [pgvector.django.indexes.IvfflatIndex(fields=['embedding'], name='chat_embed_ivf_cos', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
