# Generated by Django 5.2 on 2025-06-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_created_at_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('clinic_moderator', 'Clinic Moderator'), ('healthcarecenter_moderator', 'Healthcare Center Moderator'), ('assistant', 'Assistant')], default='patient', max_length=50),
        ),
    ]
