
services:
  db:
    build: ./postgres    
    container_name: palclinic_db
    environment:
      POSTGRES_DB: palclinic_db
      POSTGRES_USER: palclinic_user
      POSTGRES_PASSWORD: palclinic_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    container_name: palclinic_redis

  translation:
    image: python:3.11-slim
    container_name: palclinic_translation
    working_dir: /Service
    volumes:
      - ./Service:/Service            
    command: >
      sh -c "
        pip install --no-cache-dir sentencepiece torch==2.3.0 transformers==4.41.2 fastapi uvicorn &&
        uvicorn translation_service:app --app-dir /Service --host 0.0.0.0 --port 8008
      "
    ports:
      - '8008:8008'
  web:
   build: .
   container_name: palclinic_backend
   command: >
    sh -c "
      set -e &&
      echo 'Running migrations...' &&
      python manage.py migrate &&
      echo 'Starting Daphne server...' &&
      daphne -b 0.0.0.0 -p 8000 PalClinic.asgi:application
    "
   volumes:
     - .:/app
   ports:
     - '8000:8000'
   environment:
   - TRANSLATION_SERVICE_URL=http://translation:8008/translate
   depends_on:
     - db
     - redis
     

  celery:
    build: .
    container_name: palclinic_celery
    command: celery -A PalClinic worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    environment:
    - TRANSLATION_SERVICE_URL=http://translation:8008/translate

  celery-beat:
    build: .
    container_name: palclinic_beat
    command: celery -A PalClinic beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    environment:
    - TRANSLATION_SERVICE_URL=http://translation:8008/translate

volumes:
  postgres_data:
