# Generated by Django 5.2 on 2025-05-02 07:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCareCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='PalClinc', max_length=50)),
                ('centerType', models.CharField(choices=[('Goverment', 'Gov'), ('Pricvate', 'Prv'), ('None-Profit', 'Np')], default='Goverment', max_length=12)),
                ('address', models.TextField(default='UNDEFINED', max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('phoneNumber', models.TextField(default='UNDEFINED', max_length=15)),
                ('email', models.EmailField(default='UNDEFINED@UNDEFINED', max_length=100)),
                ('discrption', models.TextField(default='UNDEFINED', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
