# Generated by Django 5.2 on 2025-06-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareCenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcarecenter',
            name='is_active',
            field=models.BooleanField(default=True, max_length=7),
        ),
    ]
