# Generated by Django 5.2 on 2025-04-24 16:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalProfile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentplan',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='treatmentrevision',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='doctornote',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='file',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='lab_name',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='result',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='test_name',
        ),
        migrations.AddField(
            model_name='doctornote',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='results',
            field=models.FileField(blank=True, null=True, upload_to='lab_results/'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='allergies',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='chronic_conditions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='doctornote',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctornote',
            name='note',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='medical_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='MedicalProfile.medicalprofile'),
        ),
        migrations.AddField(
            model_name='doctornote',
            name='medical_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='MedicalProfile.medicalprofile'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='medical_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='MedicalProfile.medicalprofile'),
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('report', models.FileField(upload_to='surgery_reports/')),
                ('surgery_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performed_surgeries', to=settings.AUTH_USER_MODEL)),
                ('medical_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='MedicalProfile.medicalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(blank=True, max_length=300, null=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to=settings.AUTH_USER_MODEL)),
                ('medical_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='MedicalProfile.medicalprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='PastOperation',
        ),
        migrations.DeleteModel(
            name='TreatmentPlan',
        ),
        migrations.DeleteModel(
            name='TreatmentRevision',
        ),
    ]
