# Generated by Django 5.2 on 2025-05-03 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0002_doctoraccessrequest_delete_authorizeddoctor'),
        ('HealthCareCenter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedHealthCareCenterModerators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('healthcarecenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareCenter.healthcarecenter')),
                ('moderator', models.ForeignKey(limit_choices_to={'role': 'healthcarecenter_moderator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
