# Generated by Django 5.2 on 2025-05-05 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0004_assignclinicmoderators'),
        ('Clinic', '0002_alter_clinic_clinictype_alter_clinic_specialties'),
        ('HealthCareCenter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignClinicToHealthCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.clinic')),
                ('health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareCenter.healthcarecenter')),
            ],
        ),
        migrations.CreateModel(
            name='AssignDoctorToClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.clinic')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
