# Generated by Django 5.2 on 2025-05-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0005_assignclinictohealthcenter_assigndoctortoclinic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigndoctortoclinic',
            old_name='Clinic',
            new_name='clinic',
        ),
    ]
