# Generated by Django 5.2 on 2025-06-29 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0006_rename_clinic_assigndoctortoclinic_clinic'),
        ('Clinic', '0003_clinic_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignclinictohealthcenter',
            name='clinic',
            field=models.ForeignKey(limit_choices_to={'clinictype': 'healthcarecenter'}, on_delete=django.db.models.deletion.CASCADE, to='Clinic.clinic'),
        ),
    ]
