# Generated by Django 5.2 on 2025-06-29 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, help_text='Display name shown to users', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.SlugField(help_text='ASCII slug – internal id', max_length=95, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_.-]+$')]),
        ),
    ]
